import {
    // create naive ui
    create,
    // component
    NButton,
    NCollapse,
    NCollapseItem,
    NDescriptions,
    NDescriptionsItem,
    NDropdown,
    NTooltip,
    NIcon,
    NInput,
    NColorPicker,
    NCheckbox,
    NDivider,
    NSelect,
    NUpload,
    NUploadDragger,
    NCard,
    NTree,
    NTabs,
    NTabPane,
    NText,
    NForm,
    NFormItem,
    NInputNumber,
    NImage,
    NBadge,
    NEllipsis,
    NRadioGroup,
    NRadio,
    NRadioButton,
    NPopover,
    NP,
    NH3,
    NSlider,
    NSwitch,
    NList, NListItem, NSpin,NAlert,NModal,NDataTable,NPagination
} from 'naive-ui';

export const naive = create({
    components: [
        NButton,
        NCollapse,
        NCollapseItem,
        NDescriptions,
        NDescriptionsItem,
        NDropdown,
        NTooltip,
        NIcon,
        NInput,
        NColorPicker,
        NCheckbox,
        NDivider,
        NSelect,
        NUpload,
        NUploadDragger,
        NCard,
        NTree,
        NTabs,
        NTabPane,
        NText,
        NForm,
        NFormItem,
        NInputNumber,
        NImage,
        NBadge,
        NEllipsis,
        NRadioGroup,
        NRadio,
        NRadioButton,
        NPopover,
        NP,
        NH3,
        NSlider,
        NSwitch, NList, NListItem, NSpin,NAlert,NModal,NDataTable,NPagination
    ],
});
